[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.11.1"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_CONFIG_FUND = "false"
  NPM_FLAGS = "--no-audit --no-fund"

[[plugins]]
  package = "@netlify/plugin-nextjs"

